name: Publish

on:
  release:
    types:
      - prereleased

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn
      - run: yarn test
      - run: yarn build
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: "https://npm.pkg.github.com"
      - run: yarn publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
